version: "3.3"
services:
  db:
    image: mariadb:10.8
    container_name: corejj-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /data/corejj/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=corejj
      - MYSQL_USER=corejj
      - MYSQL_PASSWORD=corejj.cc
      - MYSQL_ROOT_PASSWORD=corejj.cc
  corejj:
    image: opencorejj/corejj-service
    container_name: corejj
    privileged: true
    restart: always
    volumes:
      - /data/corejj/service:/data/corejj
      - /data/corejj/repos:/data/repos
    ports:
      # 如果80端口被占用可替换为其他端口，例如: - "8000:80"
      - "80:80"
    environment:
      - SPUG_DOCKER_VERSION=v3.2.4
      - MYSQL_DATABASE=corejj
      - MYSQL_USER=corejj
      - MYSQL_PASSWORD=corejj.cc
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
    depends_on:
      - db
